#!/bin/bash -e

CSS_PATH='src/static/css'
SASS_PATH='src/static/sass'
SASS_FILE='src/static/sass/styles.scss'
VARIABLES_FILE="$SASS_PATH/_variables.scss"
RESETS_FILE="$SASS_PATH/_resets.scss"


if [[ ! -e "$VARIABLES_FILE" ]]; then
    echo "variables.scss doesn't exist. Creating file..."
    touch $VARIABLES_FILE
fi

if [[ ! -e "$RESETS_FILE" ]]; then
    echo "resets.scss doesn't exist. Creating file..."
    touch $RESETS_FILE
fi

if [[ -e "$SASS_FILE" ]]; then
    echo "styles.scss exists. Updating styles.scss..."
    > "$SASS_FILE"  # Cleaning again the file
else
    echo "Styles.scss doesn't exist. Creating file..."
    touch "$SASS_FILE"
fi

echo "@import 'variables.scss';" >> "$SASS_FILE"
echo "@import 'resets.scss';" >> "$SASS_FILE"

for my_file in $(ls -1 "$SASS_PATH"/*.scss | grep -vE "_variables.scss|_resets.scss|styles.scss"); do
    FILE_NAME=$(basename "$my_file")
    FILE_WO_UNDERSCORE="${FILE_NAME#_}"
    echo "@import '$FILE_WO_UNDERSCORE';" >> "$SASS_FILE"
done

echo "styles.scss updated. Watching for changes..."
sass --watch $SASS_PATH:$CSS_PATH
